### ISSUE TITLE
投票結果の配信が0票になっている

### ISSUE THREAD

**Issue by osapon** [eizi2002/ai#210]
botの不具合なのかサーバの不具合なのか分からないのですが、このbotの動作で気が付いたのでここに報告しておきます。
投票締切後に結果がサーバから送られてきますが、その結果が0票になっています。

https://gyazo.com/f9e374cf15b99126d723ab9b6e061d19

**Comment by osapon** [comment]
https://notestock.osa-p.net/users/voteguide
notestockの投票共有アカウントの「締め切った投票」に表示される結果は、0票の時に表示しない仕様になっていて、一つのサーバの受信結果がおかしいのではなく、他のサーバにも同じものが配信されているようです。

**Comment by Leies-202** [comment]
おおう、これmisskey.ioの藍やめいすきーのいあとかでは発生して無い感じですか？

**Comment by Leies-202** [comment]
投票に関与する部分はMisskey側もこのリポジトリも弄ってはないので本家の問題かサーバー自体に問題が起きてるかの筈だけど…うーん。

**Comment by sousuke0422** [comment]
うちの[ia](https://github.com/sousuke0422/ia)では私は見たことない事例かな・・・

**Comment by Leies-202** [comment]
となると普通にこの衣亜の問題…正直セリフという誰でも弄れるところ弄るぐらいしか能がないので、根本的な解決できずに投票モジュール停止処置がオチになりそう…。

**Comment by sousuke0422** [comment]
一応私の方でももう少し見てみる

**Comment by Leies-202** [comment]
わぉ、結果以前に途中経過からしてバグってるか？(1枚目はMastodon経由の投票直後。状況は反映されている。2枚目はそこから再読み込みしたところ。投票はされてる判定なのに状況は無反映。)

![image](https://user-images.githubusercontent.com/22660503/110817951-26299580-82d0-11eb-99f8-4a9c85a8046c.png)
![image](https://user-images.githubusercontent.com/22660503/110817967-2a55b300-82d0-11eb-9980-463b691fcf9b.png)

**Comment by Leies-202** [comment]
別のサーバー(めいすきーではない)のいあの投票をMastodonで覗くと、投票率が全0%になるような挙動は少なくとも見られず。

よってこのリポジトリ特有の問題になりました……。
アンケート封印で終わりそうです。
スキル無しの私がマジで悪い。申し訳ない。

![image](https://user-images.githubusercontent.com/22660503/110818813-f7f88580-82d0-11eb-8963-1c60f2be2e3c.png)

**Comment by Leies-202** [comment]
> わぉ、結果以前に途中経過からしてバグってるか？(1枚目はMastodon経由の投票直後。状況は反映されている。2枚目はそこから再読み込みしたところ。投票はされてる判定なのに状況は無反映。)
> 
> ![image](https://user-images.githubusercontent.com/22660503/110817951-26299580-82d0-11eb-99f8-4a9c85a8046c.png)
> ![image](https://user-images.githubusercontent.com/22660503/110817967-2a55b300-82d0-11eb-9980-463b691fcf9b.png)

何度か更新したら普通になった。
何が起きてるんだこれ…とりあえず結果発表待ちだ。

ちょうど別鯖のいあBotが同じく定時のアンケートしてて、voteguideにも反応されてるっぽいしそっちの挙動も見ればここ固有の問題がわかる…はず。

**Comment by Leies-202** [comment]
> ちょうど別鯖のいあBotが同じく定時のアンケートしてて、voteguideにも反応されてるっぽいしそっちの挙動も見ればここ固有の問題がわかる…はず。

はい。別鯖いあBotは結果がvoteguideに認識されてました。

このBot固有の問題と決まりました。詰み。

**Comment by osapon** [comment]
misskey.ioの自分のアカウントで投票を投稿して、マストドン側から投票したら、ちゃんと締切時の通知には反映されていたんですよね。

botが単に投票を投稿しているだけで、その後の処理がサーバ任せなら、サーバ側の問題かなと思ったのですが、サーバとbotがどこまで噛み合っているのか分からず・・・。

投票の途中経過は別の場所に保存されていて、締切に合わせて投稿情報に反映されるけど、その前に終了通知が各サーバに配布されて0票に見える、とかなのかなぁとか、misskeyの内部構造を調べずに想像したりしています。
結果反映と各サーバへの結果配布の処理が別々に動いていてタイミングによって逆になるとか。

**Comment by kintsuba** [comment]
ぱっと見、タイマーをbot内で設定して切れたら投稿しているだけのように見えるので、他サーバへの配信に問題があるとしたらサーバ側=Misskeyの方じゃないかと思います

**Comment by Leies-202** [comment]
> > ちょうど別鯖のいあBotが同じく定時のアンケートしてて、voteguideにも反応されてるっぽいしそっちの挙動も見ればここ固有の問題がわかる…はず。
> 
> はい。別鯖いあBotは結果がvoteguideに認識されてました。
> 
> このBot固有の問題と決まりました。詰み。

と思えば別鯖いあの結果も今サイト見たら履歴に残ってない謎。

多分 2021-03-11 23:05:00 の結果の上辺りに載ってないとなはずなのに…もう何がなんだか。

**Comment by osapon** [comment]
すみません。voteguideで表示されない件についてはこちらのミスでした。
ただ、最初に例で挙げた投票したのに結果が0件で届く場合がある分については謎のまま・・・。

**Comment by Leies-202** [comment]
了解です。
それはそれでこのリポジトリBotで何かやらかしてるのか、本家で既にやらかしてるのか、はたまたMisskeyでやらかしてるのか分からないな…

**Comment by Leies-202** [comment]
見づらいけどこの通知2件、普通に投票反映されてます…。

![image](https://user-images.githubusercontent.com/22660503/111875224-097e1380-89dc-11eb-918a-76fd4c40006c.png)
