### ISSUE TITLE
覚えましたが発動しない

### ISSUE THREAD

**Issue by Leies-202** [eizi2002/ai#22]
サーバー高負荷発言発言も○○…○○…覚えました発言も全く見た事がないので多分やらかしてると判断。

覚えた系はMeCabのパスミスも有り得るので難易度高め(現在コンフィグに書いてあるパスはそれをbashに打ったら起動するパス)

**Comment by Leies-202** [comment]
サーバー監視はそもそもバグだった模様。

だが言葉覚えは機能してるの見てるし何かやらかしてるはず…やらかしてるかの確認方法ないけど…。


参考:https://github.com/syuilo/ai/pull/45

**Comment by Leies-202** [comment]
とりあえずサーバーの件をマージ
https://github.com/Leies-202/ai/commit/f53dceabd991fe6383ab1c73d5129fe825fe9d9f

**Comment by Leies-202** [comment]
ログを絞って見る方法が欲しい

**Comment by Leies-202** [comment]
インスタンスの１つである 月、ネットワーク の藍BotはLTLの発言そこそこでも割と高頻度で発動してるので何をどう考えてもバグってるのが確定しました。

パスミスから確認したいが今のパスじゃないならどこが正解？(それともMeCab自体の方でやらかしている？)

**Comment by Leies-202** [comment]
【要約】
[現状考えうる原因]
~・発言後少なすぎる~ ←これは先述の理由で破棄
~・MeCabのパスミス ←ならどこ？~
・MeCabの設定ミス ←辞書とか？
・衣亜たそのセリフファイルの書き換えがマズい←別機能で前科がある為可能性がないとは言えない。

**Comment by u1-liquid** [comment]
> MeCabのパス

`which`コマンドで確認できます
```
$ which mecab
/usr/bin/mecab
```

**Comment by Leies-202** [comment]
> > MeCabのパス
> 
> `which`コマンドで確認できます
> 
> ```
> $ which mecab
> /usr/bin/mecab
> ```

🙏

**Comment by Leies-202** [comment]
パス確認の結果
`/usr/bin/mecab `

多分パスミスの可能性は消滅。

**Comment by u1-liquid** [comment]
辞典 -> Ubuntu で例えるとシステムロケールが`*.UTF-8`で
```
dpkg -l | grep mecab
```
の出力で
`mecab-ipadic-utf8`と`mecab-jumandic-utf8`さえちゃんとインスコされていたら問題ないはずです

**Comment by Leies-202** [comment]
あー、mecab-ipadic-utf8が無いので入れてみます

**Comment by Leies-202** [comment]
入れたのであとは様子見

**Comment by Leies-202** [comment]
おーん？

```
(node:25641) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at default_1.learn (/home/misskey/ai/built/modules/keyword/index.js:54:29)
(node:25641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminatethe node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict`
```

**Comment by Leies-202** [comment]
これが普通にエラーなのか、TLが静かすぎて覚える対象が見つからなくてエラったのかで話が変わるんだが...。

**Comment by Leies-202** [comment]
お～ん...該当するissueが本家の方に...。
https://github.com/syuilo/ai/issues/38

**Comment by kintsuba** [comment]
参照しているのがLTLなので、無効化している状態では機能しないと思うです

**Comment by Leies-202** [comment]
いや、モデレート権限はあるのでLTLは見れるはず...

**Comment by kintsuba** [comment]
確証はないのですが、
- `notes/local-timeline` を使用してTLを取得している
- `notes/local-timeline` は `Credential required: No` なので誰がやっても同じ結果になるはず
- 実際に LTL が無効化されているときに↑をやると、`Local timeline has been disabled` が返ってくる

以上から、TL が取得できていない可能性がかなり高いと思うです。取得直後でログ吐かせて試すです

**Comment by Leies-202** [comment]
う～ん、Webクライアントのテストコンソールからアクセスしたら権限あり(Bot)の方はアクセスできたし、WebSocketに至ってはLTL見れないはずのアカウント(要するに私のアカウント)のAPIで見れてしまった....これは...

**Comment by u1-liquid** [comment]
> これが普通にエラーなのか、TLが静かすぎて覚える対象が見つからなくてエラったのかで話が変わるんだが...。

うちも同じエラーが起きてるのを確認しましたのでおそらく動作に問題はないようです。
https://github.com/syuilo/ai/issues/38#issuecomment-579203650

**Comment by Leies-202** [comment]
> > これが普通にエラーなのか、TLが静かすぎて覚える対象が見つからなくてエラったのかで話が変わるんだが...。
> 
> うちも同じエラーが起きてるのを確認しましたのでおそらく動作に問題はないようです。
> [syuilo#38 (comment)](https://github.com/syuilo/ai/issues/38#issuecomment-579203650)

つまり後者のパターン...。

**Comment by u1-liquid** [comment]
> 確証はないのですが、
> 
> * `notes/local-timeline` を使用してTLを取得している
> * `notes/local-timeline` は `Credential required: No` なので誰がやっても同じ結果になるはず
> * 実際に LTL が無効化されているときに↑をやると、`Local timeline has been disabled` が返ってくる
> 
> 以上から、TL が取得できていない可能性がかなり高いと思うです。取得直後でログ吐かせて試すです

https://github.com/syuilo/misskey/blob/c8ba5add8cc9adf53f25ff01c84fc8663e263dce/src/server/api/endpoints/notes/local-timeline.ts#L87

`notes/local-timeline` はたしか`Credential required: No`ですがログイン状態のユーザーなら当然ログイン情報が渡されるので、モデレーター以上だとLTLを見れるようになっています。

**Comment by Leies-202** [comment]
う～ん、となるとやはりTLが静かすぎるだけというオチに...?

**Comment by u1-liquid** [comment]
れいじゅぼっととか入れてみたらどうでしょう👀

**Comment by kintsuba** [comment]
固有名詞投げまくればいいだけなのでは……

**Comment by Leies-202** [comment]
> 固有名詞投げまくればいいだけなのでは……

解決策といえる解決策はそれですね...。

**Comment by Leies-202** [comment]
結局(間隔を狭めて終わり)
https://misskey.lei202.com/notes/716fec36b3e87d1f424b5f1b
